from apps.core.extensions.extenders import (
    AdminNavigationExtender,
    AdminSurfaceExtender,
    ApiResourceExtender,
    ApiRoutesExtender,
    AuthExtender,
    ConditionalExtender,
    ConsoleExtender,
    CsrfExtender,
    DiscussionLifecycleExtender,
    ErrorHandlingExtender,
    EventListenersExtender,
    FilesystemExtender,
    ForumCapabilitiesExtender,
    FormatterExtender,
    FrontendExtender,
    LanguagePackExtender,
    LifecycleExtender,
    LifecycleInterface,
    LinkExtender,
    LocalesExtender,
    MiddlewareExtender,
    ModelExtender,
    ModelPrivateExtender,
    ModelUrlExtender,
    ModelVisibilityExtender,
    NotificationsExtender,
    PolicyExtender,
    PostExtender,
    RealtimeExtender,
    ResourceExtender,
    RoutesExtender,
    SearchDriverExtender,
    SearchIndexExtender,
    SessionExtender,
    ServiceProviderExtender,
    ThemeExtender,
    ThrottleApiExtender,
    UserExtender,
    RuntimeActionsExtender,
    SettingsExtender,
)

__all__ = [
    "AdminNavigationExtender",
    "AdminSurfaceExtender",
    "ApiResourceExtender",
    "ApiRoutesExtender",
    "AuthExtender",
    "ConditionalExtender",
    "ConsoleExtender",
    "CsrfExtender",
    "DiscussionLifecycleExtender",
    "ErrorHandlingExtender",
    "EventListenersExtender",
    "FilesystemExtender",
    "ForumCapabilitiesExtender",
    "FormatterExtender",
    "FrontendExtender",
    "LanguagePackExtender",
    "LifecycleExtender",
    "LifecycleInterface",
    "LinkExtender",
    "LocalesExtender",
    "MiddlewareExtender",
    "ModelExtender",
    "ModelPrivateExtender",
    "ModelUrlExtender",
    "ModelVisibilityExtender",
    "NotificationsExtender",
    "PolicyExtender",
    "PostExtender",
    "RealtimeExtender",
    "ResourceExtender",
    "RoutesExtender",
    "SearchDriverExtender",
    "SearchIndexExtender",
    "SessionExtender",
    "ServiceProviderExtender",
    "ThemeExtender",
    "ThrottleApiExtender",
    "UserExtender",
    "RuntimeActionsExtender",
    "SettingsExtender",
    "get_extension_registry",
]


def get_extension_registry():
    from apps.core.extensions.registry import get_extension_registry as _get_extension_registry

    return _get_extension_registry()
