# Generated by Django 5.0.3 on 2026-06-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_extension_installations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="extensioninstallation",
            new_name="extension_i_extensi_9e9d37_idx",
            old_name="extension_in_extensi_170d92_idx",
        ),
        migrations.RenameIndex(
            model_name="extensioninstallation",
            new_name="extension_i_enabled_28cd11_idx",
            old_name="extension_in_enabled_4a7295_idx",
        ),
        migrations.RenameIndex(
            model_name="extensioninstallation",
            new_name="extension_i_install_66f4a9_idx",
            old_name="extension_in_installe_2c2d6e_idx",
        ),
    ]
