import {
  registerAdminAdvancedPageActionMeta,
  registerAdminAdvancedPageConfig,
  registerAdminAdvancedPageCopy,
} from '../pages.js'

registerAdminAdvancedPageCopy({
  key: 'core-advanced-page-copy',
  order: 10,
  resolve: () => ({
    pageTitle: '高级设置',
    pageDescription: '配置缓存、队列、维护模式与文件存储',
    runtimeNoticeTitle: '运行时说明',
    immediateEffectTitle: '即时生效',
    immediateEffectDescription: '`maintenance_mode`、`maintenance_message`、`cache_lifetime`、`log_queries` 会在保存后直接影响请求层行为。',
    deploymentRequiredTitle: '需额外部署或重启',
    deploymentRequiredDescription: '`debug_mode` 由 Django 配置文件或环境变量控制；`queue_enabled` / `queue_driver` 会控制已接入队列入口的任务，新 worker 配置需重启服务后生效。',
    dependencyHealthTitle: '依赖健康',
    dependencyHealthHelpText: '查看缓存、实时层、队列 broker 与 worker 的当前运行状态。',
    dependencyActionLabel: '建议处理',
    cacheSectionTitle: '缓存设置',
    cacheDriverLabel: '缓存驱动',
    cacheDriverHelpText: '选择缓存存储方式',
    cacheLifetimeLabel: '缓存时间（秒）',
    cacheLifetimeHelpText: '当前已接入公开论坛设置缓存。填 0 表示禁用该缓存，保存基础/外观/高级设置时会自动清理。',
    clearCacheLabel: '清除缓存',
    clearingCacheLabel: '清除中...',
    searchSectionTitle: '搜索索引',
    searchStatusLabel: '当前状态',
    searchStatusHintText: '查看当前索引与队列运行状态。',
    searchStatusLoadingText: '加载中...',
    searchDatabaseLabel: '当前数据库',
    searchLastRebuildLabel: '最近重建',
    searchNeverRebuiltText: '尚未重建',
    searchLastRebuildDurationFallback: '最近一次重建未记录耗时。',
    searchLastRebuildDurationText: durationMs => `最近一次耗时 ${durationMs} ms`,
    searchQueueStatusLabel: '索引队列状态',
    searchQueueStatusHelpText: '当前重建按钮仍是请求内执行，后续异步索引任务会复用这里的队列运行状态。',
    searchMissingIndexesLabel: '缺失索引',
    searchIndexLabel: 'PostgreSQL 全文索引',
    searchIndexHelpText: '用于英文、数字关键词的讨论、回复和用户搜索。数据量较大时请在低峰期执行。',
    rebuildSearchIndexesLabel: '重建搜索索引',
    rebuildingSearchIndexesLabel: '重建中...',
    queueSectionTitle: '队列设置',
    queueDriverLabel: '队列驱动',
    queueDriverHelpText: '当前通知实时投递已接入统一队列入口。选择 Redis 并部署 worker 后会尝试异步投递。',
    queueEnabledLabel: '启用队列处理',
    queueEnabledHelpText: '关闭时强制同步执行。开启后，已接入任务会入队执行；入队失败时会同步回退，避免影响主流程。',
    realtimeTypingEnabledLabel: '启用回复输入提示',
    realtimeTypingEnabledHelpText: '关闭后，讨论详情页不再广播“正在输入”状态；仍保留其他实时通知与更新。',
    humanVerificationSectionTitle: '安全与真人验证',
    humanVerificationProviderLabel: '验证提供方',
    humanVerificationProviderHelpText: '建议正式环境开启，优先拦截登录和注册机器人。',
    turnstileSiteKeyLabel: 'Site Key',
    turnstileSecretKeyLabel: 'Secret Key',
    turnstileLoginEnabledLabel: '登录时启用真人验证',
    turnstileRegisterEnabledLabel: '注册时启用真人验证',
    turnstileMisconfiguredText: '已选择 Turnstile，但 Site Key 或 Secret Key 仍为空，当前不会真正启用验证。',
    storageSectionTitle: '文件存储',
    storageDriverLabel: '存储驱动',
    storageDriverHelpText: 'Composer 上传、头像上传和后续附件能力都会读取这里的运行时配置',
    storageAttachmentsDirLabel: '附件目录',
    storageAttachmentsDirHelpText: '统一的附件对象目录，支持多级路径',
    storageAvatarsDirLabel: '头像目录',
    storageAvatarsDirHelpText: '头像和缩略图的对象目录',
    uploadPolicyTitle: '上传策略',
    uploadPolicyDescription: '限制上传大小，扩展名白名单仍由服务端固定控制。',
    uploadAvatarMaxSizeLabel: '头像最大体积（MB）',
    uploadAttachmentMaxSizeLabel: '附件最大体积（MB）',
    uploadSiteAssetMaxSizeLabel: '站点资源最大体积（MB）',
    uploadSizeHelpText: '头像默认 2MB，Composer 附件默认 10MB，Logo/Favicon 默认 2MB。',
    localPathLabel: '本地保存目录',
    localPathHelpText: '可填写绝对路径，也可填写相对项目根目录的路径',
    localBaseUrlLabel: '本地访问基地址',
    localBaseUrlHelpText: '上传完成后生成给前台的 URL 前缀',
    bucketLabel: 'Bucket',
    regionLabel: 'Region',
    endpointLabel: 'Endpoint',
    publicUrlLabel: '公共访问 URL',
    publicUrlCdnLabel: '公共访问 URL / CDN 域名',
    s3EndpointHelpText: '使用 MinIO、Wasabi 等兼容服务时填写自定义 Endpoint',
    s3PublicUrlHelpText: '如留空，系统会按标准 S3 域名尝试拼接',
    accessKeyIdLabel: 'Access Key ID',
    secretAccessKeyLabel: 'Secret Access Key',
    accessKeySecretLabel: 'Access Key Secret',
    objectPrefixLabel: '对象前缀',
    pathStyleLabel: '使用 Path Style',
    pathStyleHelpText: '兼容部分 S3 服务或自建对象存储',
    r2PublicUrlHelpText: 'R2 通常需要单独的公开域名，否则前台生成的附件链接不可访问',
    ossPublicUrlHelpText: '如留空，将按 Bucket + Endpoint 生成标准 OSS 访问地址',
    imagebedEndpointLabel: '上传接口地址',
    imagebedMethodLabel: '请求方法',
    imagebedFileFieldLabel: '文件字段名',
    imagebedUrlPathLabel: '响应 URL 路径',
    imagebedUrlPathHelpText: '支持点路径，例如 `data.url`、`result.images.0.url`',
    imagebedHeadersLabel: '请求头 JSON',
    imagebedFormDataLabel: '额外表单参数 JSON',
    maintenanceSectionTitle: '维护模式',
    maintenanceEnabledLabel: '启用维护模式',
    maintenanceEnabledHelpText: '启用后，普通用户访问论坛 API 将收到 503；`/api/forum`、登录接口和后台入口保留豁免。',
    maintenanceMessageLabel: '维护提示信息',
    extensionSafeModeLabel: '启用扩展恢复模式',
    extensionSafeModeHelpText: '启用后只启动内置扩展和白名单扩展，用于排查扩展导致的启动或运行异常。',
    extensionSafeModeExtensionsLabel: '恢复模式扩展白名单',
    extensionSafeModeExtensionsHelpText: '填写扩展 ID，多个扩展用英文逗号分隔。留空时只启动内置扩展。',
    debugSectionTitle: '调试设置',
    debugModeLabel: '调试模式（只读）',
    debugModeHelpText: '当前运行值来自 Django 配置文件或环境变量，保存这里不会热切换服务端 DEBUG。',
    logQueriesLabel: '记录数据库查询',
    logQueriesHelpText: '保存后即时生效。会把每个 HTTP 请求触发的 SQL 记录到服务器日志。',
    saveLabel: '保存设置',
    savingLabel: '保存中...',
    saveSuccessText: '保存成功',
    saveErrorText: '保存失败，请重试',
  }),
})

registerAdminAdvancedPageConfig({
  key: 'core-advanced-page-config',
  order: 10,
  resolve: () => ({
    defaultSettings: {
      cache_driver: 'file',
      cache_lifetime: 3600,
      queue_driver: 'sync',
      queue_enabled: false,
      realtime_typing_enabled: true,
      maintenance_mode: false,
      maintenance_mode_key: 'none',
      maintenance_message: '',
      extension_safe_mode: false,
      extension_safe_mode_extensions: [],
      debug_mode: false,
      log_queries: false,
      auth_human_verification_provider: 'off',
      auth_turnstile_site_key: '',
      auth_turnstile_secret_key: '',
      auth_human_verification_login_enabled: true,
      auth_human_verification_register_enabled: true,
      storage_driver: 'local',
      storage_attachments_dir: 'attachments',
      storage_avatars_dir: 'avatars',
      upload_avatar_max_size_mb: 2,
      upload_attachment_max_size_mb: 10,
      upload_site_asset_max_size_mb: 2,
      storage_local_path: '',
      storage_local_base_url: '/media/',
      storage_s3_bucket: '',
      storage_s3_region: '',
      storage_s3_endpoint: '',
      storage_s3_access_key_id: '',
      storage_s3_secret_access_key: '',
      storage_s3_public_url: '',
      storage_s3_object_prefix: '',
      storage_s3_path_style: false,
      storage_r2_bucket: '',
      storage_r2_endpoint: '',
      storage_r2_access_key_id: '',
      storage_r2_secret_access_key: '',
      storage_r2_public_url: '',
      storage_r2_object_prefix: '',
      storage_oss_bucket: '',
      storage_oss_endpoint: '',
      storage_oss_access_key_id: '',
      storage_oss_access_key_secret: '',
      storage_oss_public_url: '',
      storage_oss_object_prefix: '',
      storage_imagebed_endpoint: '',
      storage_imagebed_method: 'POST',
      storage_imagebed_file_field: 'file',
      storage_imagebed_headers: '{}',
      storage_imagebed_form_data: '{}',
      storage_imagebed_url_path: 'data.url',
    },
    defaultRuntimeDependencyChecks: [],
    placeholders: {
      cacheLifetime: '3600',
      turnstileSiteKey: '0x4AAAA...',
      turnstileSecretKey: '0x4AAAA...',
      storageAttachmentsDir: 'attachments',
      storageAvatarsDir: 'avatars',
      storageLocalPath: 'D:\\data\\bias\\media',
      storageLocalBaseUrl: '/media/',
      storageS3Region: 'ap-southeast-1',
      storageS3Endpoint: 'https://s3.amazonaws.com',
      storageS3PublicUrl: 'https://cdn.example.com',
      storageObjectPrefix: 'bias',
      storageR2Endpoint: 'https://<accountid>.r2.cloudflarestorage.com',
      storageR2PublicUrl: 'https://pub-xxx.r2.dev',
      storageOssEndpoint: 'oss-cn-hangzhou.aliyuncs.com',
      imagebedEndpoint: 'https://example.com/api/upload',
      imagebedFileField: 'file',
      imagebedUrlPath: 'data.url',
      imagebedHeaders: '{\"Authorization\":\"Bearer token\"}',
      imagebedFormData: '{\"album\":\"forum\"}',
      maintenanceMessage: '论坛正在维护中，请稍后再试...',
      extensionSafeModeExtensions: 'tags, notifications',
    },
    cacheDriverOptions: [
      { value: 'file', label: '文件' },
      { value: 'redis', label: 'Redis' },
      { value: 'memcached', label: 'Memcached' },
    ],
    queueDriverOptions: [
      { value: 'sync', label: '同步' },
      { value: 'database', label: '数据库' },
      { value: 'redis', label: 'Redis' },
    ],
    humanVerificationProviderOptions: [
      { value: 'off', label: '关闭' },
      { value: 'turnstile', label: 'Cloudflare Turnstile' },
    ],
    storageDriverOptions: [
      { value: 'local', label: '本地存储' },
      { value: 's3', label: 'Amazon S3 / S3 兼容' },
      { value: 'r2', label: 'Cloudflare R2' },
      { value: 'oss', label: '阿里云 OSS' },
      { value: 'imagebed', label: '通用图床' },
    ],
    imagebedMethodOptions: [
      { value: 'POST', label: 'POST' },
      { value: 'PUT', label: 'PUT' },
      { value: 'PATCH', label: 'PATCH' },
    ],
    maintenanceModeOptions: [
      { value: 'none', label: '关闭' },
      { value: 'low', label: '低维护' },
      { value: 'high', label: '高维护' },
      { value: 'safe', label: '恢复模式' },
    ],
    sensitiveLabels: {
      maintenance_mode: '维护模式',
      maintenance_mode_key: '维护级别',
      extension_safe_mode: '扩展恢复模式',
      extension_safe_mode_extensions: '恢复模式扩展白名单',
      queue_enabled: '队列启用状态',
      realtime_typing_enabled: '回复输入提示',
      queue_driver: '队列驱动',
      log_queries: 'SQL 查询日志',
      storage_driver: '文件存储驱动',
      upload_avatar_max_size_mb: '头像上传上限',
      upload_attachment_max_size_mb: '附件上传上限',
      upload_site_asset_max_size_mb: '站点资源上传上限',
    },
  }),
})

registerAdminAdvancedPageActionMeta({
  key: 'core-advanced-page-actions-meta',
  order: 10,
  resolve: () => ({
    loadErrorText: '加载高级设置失败，请稍后重试',
    saveConfirmTitle: '保存高级设置',
    saveConfirmMessage: changes => `以下设置会影响运行时行为：${changes.join('、')}。确定保存当前配置吗？`,
    saveConfirmText: '保存',
    saveCancelText: '取消',
    clearCacheConfirmTitle: '清除缓存',
    clearCacheConfirmMessage: '确定清除运行时缓存吗？短时间内部分页面可能重新读取配置和数据。',
    clearCacheConfirmText: '清除',
    clearCacheCancelText: '取消',
    clearCacheSuccessTitle: '缓存已清除',
    clearCacheSuccessMessage: '运行时缓存已成功清理。',
    clearCacheFailedTitle: '清除缓存失败',
    loadSearchStatusErrorText: '加载搜索索引状态失败，请稍后重试',
    rebuildSearchConfirmTitle: '重建搜索索引',
    rebuildSearchConfirmMessage: '确定在后台重建 PostgreSQL 全文搜索索引吗？数据量较大时可能耗时较长，建议在低峰期执行。',
    rebuildSearchConfirmText: '重建',
    rebuildSearchCancelText: '取消',
    rebuildSearchSuccessTitle: '搜索索引已重建',
    rebuildSearchSuccessMessage: result => `已重建 ${Array.isArray(result?.indexes) ? result.indexes.length : 0} 个搜索索引。`,
    rebuildSearchFailedTitle: '重建搜索索引失败',
    unknownErrorText: '未知错误',
  }),
})
