# Generated by plan_target_environment_evidence.
# Contains only safe_to_run_unattended=true archive commands with no substitution tokens.
# Manual approval, final validation, destructive, and substitution-required commands are intentionally excluded.
# Output directories are created before command redirection.
$ErrorActionPreference = 'Stop'

New-Item -ItemType Directory -Force -Path 'D:\files\project\tmp\bias\reports\capacity\20260702-025600' | Out-Null

python manage.py install_forum --database postgres --config instance/site.json --non-interactive --dry-run --format json > 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\install-forum-dry-run.json' 2> 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\install-forum-dry-run.stderr.txt'
python manage.py upgrade_forum --config instance/site.json --dry-run --non-interactive --format json > 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\upgrade-forum-dry-run.json' 2> 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\upgrade-forum-dry-run.stderr.txt'
python manage.py smoke_runtime_integrations --smtp-connect --storage-write --require-smtp-connect --require-storage-write --require-object-storage --fail-on-warning --format json > 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\smoke-runtime-integrations.json' 2> 'D:\files\project\tmp\bias\reports\capacity\20260702-025600\smoke-runtime-integrations.stderr.txt'
