export {
  getAdminDashboardActions,
  getAdminNavSections,
  getAdminRoutes,
  registerAdminRoute,
} from './registry/routes.js'
export {
  getAdminDashboardAction,
  getAdminDashboardActionMeta,
  getAdminDashboardAlerts,
  getAdminDashboardConfig,
  getAdminDashboardCopy,
  getAdminDashboardQueueMetrics,
  getAdminDashboardStats,
  getAdminDashboardStatusBadges,
  getAdminDashboardStatusItems,
  getAdminDashboardStatusSummaries,
  registerAdminDashboardAction,
  registerAdminDashboardActionMeta,
  registerAdminDashboardAlert,
  registerAdminDashboardConfig,
  registerAdminDashboardCopy,
  registerAdminDashboardQueueMetric,
  registerAdminDashboardStat,
  registerAdminDashboardStatusBadge,
  registerAdminDashboardStatusItem,
  registerAdminDashboardStatusSummary,
} from './registry/dashboard.js'
export {
  getAdminAdvancedPageActionMeta,
  getAdminAdvancedPageConfig,
  getAdminAdvancedPageCopy,
  getAdminAppearancePageActionMeta,
  getAdminAppearancePageConfig,
  getAdminAppearancePageCopy,
  getAdminApprovalQueueNoteTemplates,
  getAdminApprovalQueuePageActionMeta,
  getAdminApprovalQueuePageConfig,
  getAdminApprovalQueuePageCopy,
  getAdminAuditLogsPageConfig,
  getAdminAuditLogsPageCopy,
  getAdminBasicsPageActionMeta,
  getAdminBasicsPageConfig,
  getAdminBasicsPageCopy,
  getAdminFlagsPageActionMeta,
  getAdminFlagsPageConfig,
  getAdminFlagsPageCopy,
  getAdminMailPageActionMeta,
  getAdminMailPageConfig,
  getAdminMailPageCopy,
  getAdminModulesPageActionMeta,
  getAdminModulesPageConfig,
  getAdminModulesPageCopy,
  getAdminPermissionsPageActionMeta,
  getAdminPermissionsPageConfig,
  getAdminPermissionsPageCopy,
  getAdminTagsPageActionMeta,
  getAdminTagsPageConfig,
  getAdminTagsPageCopy,
  getAdminUsersPageActionMeta,
  getAdminUsersPageConfig,
  getAdminUsersPageCopy,
  registerAdminAdvancedPageActionMeta,
  registerAdminAdvancedPageConfig,
  registerAdminAdvancedPageCopy,
  registerAdminAppearancePageActionMeta,
  registerAdminAppearancePageConfig,
  registerAdminAppearancePageCopy,
  registerAdminApprovalQueueNoteTemplate,
  registerAdminApprovalQueuePageActionMeta,
  registerAdminApprovalQueuePageConfig,
  registerAdminApprovalQueuePageCopy,
  registerAdminAuditLogsPageConfig,
  registerAdminAuditLogsPageCopy,
  registerAdminBasicsPageActionMeta,
  registerAdminBasicsPageConfig,
  registerAdminBasicsPageCopy,
  registerAdminFlagsPageActionMeta,
  registerAdminFlagsPageConfig,
  registerAdminFlagsPageCopy,
  registerAdminMailPageActionMeta,
  registerAdminMailPageConfig,
  registerAdminMailPageCopy,
  registerAdminModulesPageActionMeta,
  registerAdminModulesPageConfig,
  registerAdminModulesPageCopy,
  registerAdminPermissionsPageActionMeta,
  registerAdminPermissionsPageConfig,
  registerAdminPermissionsPageCopy,
  registerAdminTagsPageActionMeta,
  registerAdminTagsPageConfig,
  registerAdminTagsPageCopy,
  registerAdminUsersPageActionMeta,
  registerAdminUsersPageConfig,
  registerAdminUsersPageCopy,
} from './registry/pages.js'

import './registry/bootstrap/routes.js'
import './registry/bootstrap/dashboard.js'
import './registry/bootstrap/modulesPage.js'
import './registry/bootstrap/basicsPage.js'
import './registry/bootstrap/appearancePage.js'
import './registry/bootstrap/mailPage.js'
import './registry/bootstrap/advancedPage.js'
import './registry/bootstrap/tagsPage.js'
import './registry/bootstrap/auditLogsPage.js'
import './registry/bootstrap/approvalQueuePage.js'
import './registry/bootstrap/flagsPage.js'
import './registry/bootstrap/permissionsPage.js'
import './registry/bootstrap/usersPage.js'
