from __future__ import annotations

from apps.core.forum_registry_search import (
    _apply_all_discussion_list_filter,
    _apply_discussion_author_search_filter,
    _apply_discussion_created_month_search_filter,
    _apply_discussion_latest_sort,
    _apply_discussion_locked_search_filter,
    _apply_discussion_newest_sort,
    _apply_discussion_oldest_sort,
    _apply_discussion_sticky_search_filter,
    _apply_discussion_top_sort,
    _apply_discussion_unread_search_filter,
    _apply_discussion_unanswered_sort,
    _apply_my_discussions_list_filter,
    _apply_post_author_search_filter,
    _apply_post_created_month_search_filter,
    _apply_unread_discussions_list_filter,
    _parse_author_search_filter,
    _parse_created_month_search_filter,
    _parse_locked_search_filter,
    _parse_sticky_search_filter,
    _parse_unread_search_filter,
)
from apps.core.forum_registry_types import (
    AdminPageDefinition,
    DiscussionListFilterDefinition,
    DiscussionSortDefinition,
    EventListenerDefinition,
    ForumModuleDefinition,
    LanguagePackDefinition,
    PermissionDefinition,
    PostTypeDefinition,
    SearchFilterDefinition,
)


def _register_core_modules(registry) -> None:
    registry.register_module(
        ForumModuleDefinition(
            module_id="core",
            name="Core",
            description="论坛核心配置、权限、外观与高级设置底座。",
            category="core",
            is_core=True,
            admin_pages=(
                AdminPageDefinition(
                    path="/admin",
                    label="仪表盘",
                    icon="fas fa-chart-bar",
                    module_id="core",
                    nav_section="core",
                    description="查看论坛概况和系统状态。",
                ),
                AdminPageDefinition(
                    path="/admin/basics",
                    label="基础设置",
                    icon="fas fa-pencil-alt",
                    module_id="core",
                    nav_section="core",
                    description="维护论坛标题、公告与 SEO 基础信息。",
                    settings_group="basic",
                ),
                AdminPageDefinition(
                    path="/admin/permissions",
                    label="权限管理",
                    icon="fas fa-key",
                    module_id="core",
                    nav_section="core",
                    description="配置用户组权限矩阵。",
                ),
                AdminPageDefinition(
                    path="/admin/appearance",
                    label="外观设置",
                    icon="fas fa-paint-brush",
                    module_id="core",
                    nav_section="core",
                    description="维护主题色、Logo 与自定义样式。",
                    settings_group="appearance",
                ),
                AdminPageDefinition(
                    path="/admin/mail",
                    label="邮件设置",
                    icon="fas fa-envelope",
                    module_id="core",
                    nav_section="feature",
                    description="配置邮件驱动与测试投递。",
                    settings_group="mail",
                ),
                AdminPageDefinition(
                    path="/admin/advanced",
                    label="高级设置",
                    icon="fas fa-cog",
                    module_id="core",
                    nav_section="feature",
                    description="管理缓存、队列、存储和维护模式。",
                    settings_group="advanced",
                ),
                AdminPageDefinition(
                    path="/admin/audit-logs",
                    label="审计日志",
                    icon="fas fa-clipboard-list",
                    module_id="core",
                    nav_section="feature",
                    description="查看后台关键管理操作审计记录。",
                ),
                AdminPageDefinition(
                    path="/admin/docs",
                    label="开发者文档",
                    icon="fas fa-book",
                    module_id="core",
                    nav_section="feature",
                    description="查看模块开发、资源字段、事件订阅与前后端接入指南。",
                ),
            ),
            capabilities=(
                "settings",
                "permissions",
                "appearance",
                "mail",
                "advanced",
                "audit-log",
                "developer-docs",
            ),
            settings_groups=("basic", "appearance", "mail", "advanced"),
            language_packs=(
                LanguagePackDefinition(
                    code="zh-CN",
                    label="简体中文",
                    native_label="简体中文",
                    module_id="core",
                    description="论坛内置默认语言包，仅提供中文界面元数据。",
                    is_default=True,
                ),
            ),
        )
    )

    registry.register_module(
        ForumModuleDefinition(
            module_id="discussions",
            name="Discussions",
            description="讨论、回复与内容管理的核心论坛能力。",
            category="feature",
            permissions=(
                PermissionDefinition(
                    code="viewForum",
                    label="查看论坛",
                    section="view",
                    section_label="查看权限",
                    module_id="discussions",
                    icon="fas fa-eye",
                    description="允许访问论坛讨论流和讨论详情。",
                ),
                PermissionDefinition(
                    code="startDiscussion",
                    label="发起讨论",
                    section="start",
                    section_label="发帖权限",
                    module_id="discussions",
                    icon="fas fa-edit",
                    description="允许创建新讨论。",
                ),
                PermissionDefinition(
                    code="startDiscussionWithoutApproval",
                    label="发起讨论免审核",
                    section="start",
                    section_label="发帖权限",
                    module_id="discussions",
                    icon="fas fa-user-check",
                    description="发起讨论后直接公开，无需进入审核队列。",
                    required_permissions=("startDiscussion",),
                ),
                PermissionDefinition(
                    code="discussion.reply",
                    label="回复讨论",
                    section="reply",
                    section_label="回复权限",
                    module_id="discussions",
                    icon="fas fa-reply",
                    description="允许在讨论中发布回复。",
                    required_permissions=("viewForum",),
                ),
                PermissionDefinition(
                    code="replyWithoutApproval",
                    label="回复免审核",
                    section="reply",
                    section_label="回复权限",
                    module_id="discussions",
                    icon="fas fa-user-check",
                    description="回复后直接公开，无需进入审核队列。",
                    required_permissions=("discussion.reply",),
                ),
                PermissionDefinition(
                    code="discussion.typing",
                    label="发送输入提示",
                    section="reply",
                    section_label="回复权限",
                    module_id="discussions",
                    icon="fas fa-keyboard",
                    description="允许在讨论实时流里向其他用户显示“正在输入”提示。",
                    required_permissions=("discussion.reply",),
                ),
                PermissionDefinition(
                    code="discussion.editOwn",
                    label="编辑自己的帖子",
                    section="reply",
                    section_label="回复权限",
                    module_id="discussions",
                    icon="fas fa-pencil-alt",
                    description="允许作者编辑自己的讨论首帖或回复。",
                ),
                PermissionDefinition(
                    code="discussion.deleteOwn",
                    label="删除自己的帖子",
                    section="reply",
                    section_label="回复权限",
                    module_id="discussions",
                    icon="fas fa-times",
                    description="允许作者删除自己的讨论或回复。",
                ),
                PermissionDefinition(
                    code="discussion.edit",
                    label="编辑任意帖子",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-pencil-alt",
                    description="允许管理任意讨论首帖与回复。",
                    required_permissions=("viewForum",),
                ),
                PermissionDefinition(
                    code="discussion.delete",
                    label="删除任意帖子",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-trash",
                    description="允许删除任意讨论或回复。",
                    required_permissions=("discussion.hide",),
                ),
                PermissionDefinition(
                    code="discussion.hide",
                    label="隐藏内容",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-eye-slash",
                    description="允许隐藏或恢复讨论内容。",
                    required_permissions=("viewForum",),
                ),
                PermissionDefinition(
                    code="discussion.rename",
                    label="重命名讨论",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-heading",
                    description="允许修改讨论标题。",
                    required_permissions=("viewForum",),
                ),
                PermissionDefinition(
                    code="discussion.lock",
                    label="锁定讨论",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-lock",
                    description="允许锁定或解锁讨论。",
                    required_permissions=("viewForum",),
                ),
                PermissionDefinition(
                    code="discussion.sticky",
                    label="置顶讨论",
                    section="moderate",
                    section_label="内容管理",
                    module_id="discussions",
                    icon="fas fa-thumbtack",
                    description="允许置顶或取消置顶讨论。",
                    required_permissions=("viewForum",),
                ),
            ),
            capabilities=("discussion-list", "discussion-detail", "composer", "moderation"),
            dependencies=("posts",),
            discussion_sorts=(
                DiscussionSortDefinition(
                    code="latest",
                    label="最新活跃",
                    module_id="discussions",
                    applier=_apply_discussion_latest_sort,
                    description="按最后活跃时间排序，优先展示最近有新回复的讨论。",
                    icon="fas fa-clock",
                    is_default=True,
                    order=10,
                    toolbar_visible=True,
                ),
                DiscussionSortDefinition(
                    code="newest",
                    label="新主题",
                    module_id="discussions",
                    applier=_apply_discussion_newest_sort,
                    description="按讨论创建时间倒序，优先展示最新发布的主题。",
                    icon="fas fa-file-alt",
                    order=20,
                    toolbar_visible=True,
                ),
                DiscussionSortDefinition(
                    code="top",
                    label="热门",
                    module_id="discussions",
                    applier=_apply_discussion_top_sort,
                    description="按回复数和浏览量综合排序，优先展示热门讨论。",
                    icon="fas fa-fire",
                    order=30,
                    toolbar_visible=True,
                ),
                DiscussionSortDefinition(
                    code="unanswered",
                    label="零回复",
                    module_id="discussions",
                    applier=_apply_discussion_unanswered_sort,
                    description="优先展示还没有收到其他回复的讨论，便于发现待回应主题。",
                    icon="fas fa-comment-slash",
                    order=40,
                    toolbar_visible=False,
                ),
                DiscussionSortDefinition(
                    code="oldest",
                    label="最早发布",
                    module_id="discussions",
                    applier=_apply_discussion_oldest_sort,
                    description="按讨论创建时间正序排序。",
                    icon="fas fa-hourglass-start",
                    order=50,
                    toolbar_visible=False,
                ),
            ),
            discussion_list_filters=(
                DiscussionListFilterDefinition(
                    code="all",
                    label="全部讨论",
                    module_id="discussions",
                    applier=_apply_all_discussion_list_filter,
                    description="显示当前可见的全部讨论。",
                    icon="far fa-comments",
                    is_default=True,
                    order=10,
                    route_path="/",
                ),
                DiscussionListFilterDefinition(
                    code="my",
                    label="我发起的",
                    module_id="discussions",
                    applier=_apply_my_discussions_list_filter,
                    description="仅显示当前用户自己发起的讨论。",
                    icon="fas fa-user",
                    requires_authenticated_user=True,
                    order=30,
                    sidebar_visible=False,
                ),
                DiscussionListFilterDefinition(
                    code="unread",
                    label="未读",
                    module_id="discussions",
                    applier=_apply_unread_discussions_list_filter,
                    description="仅显示当前用户仍有未读回复的讨论。",
                    icon="fas fa-circle",
                    requires_authenticated_user=True,
                    order=40,
                    sidebar_visible=False,
                ),
            ),
            search_filters=(
                SearchFilterDefinition(
                    code="author",
                    label="按作者过滤",
                    module_id="discussions",
                    target="discussion",
                    parser=_parse_author_search_filter,
                    applier=_apply_discussion_author_search_filter,
                    syntax="author:<username>",
                    description="按讨论作者用户名过滤搜索结果。",
                ),
                SearchFilterDefinition(
                    code="author",
                    label="按作者过滤",
                    module_id="discussions",
                    target="post",
                    parser=_parse_author_search_filter,
                    applier=_apply_post_author_search_filter,
                    syntax="author:<username>",
                    description="按回复作者用户名过滤搜索结果。",
                ),
                SearchFilterDefinition(
                    code="is_sticky",
                    label="仅置顶讨论",
                    module_id="discussions",
                    target="discussion",
                    parser=_parse_sticky_search_filter,
                    applier=_apply_discussion_sticky_search_filter,
                    syntax="is:sticky",
                    description="仅返回已置顶的讨论。",
                ),
                SearchFilterDefinition(
                    code="is_locked",
                    label="仅锁定讨论",
                    module_id="discussions",
                    target="discussion",
                    parser=_parse_locked_search_filter,
                    applier=_apply_discussion_locked_search_filter,
                    syntax="is:locked",
                    description="仅返回已锁定的讨论。",
                ),
                SearchFilterDefinition(
                    code="is_unread",
                    label="仅未读讨论",
                    module_id="discussions",
                    target="discussion",
                    parser=_parse_unread_search_filter,
                    applier=_apply_discussion_unread_search_filter,
                    syntax="is:unread",
                    description="仅返回当前用户还有未读回复的讨论。",
                ),
                SearchFilterDefinition(
                    code="created",
                    label="按创建月份过滤",
                    module_id="discussions",
                    target="discussion",
                    parser=_parse_created_month_search_filter,
                    applier=_apply_discussion_created_month_search_filter,
                    syntax="created:YYYY-MM",
                    description="按讨论创建月份过滤搜索结果。",
                ),
                SearchFilterDefinition(
                    code="created",
                    label="按创建月份过滤",
                    module_id="posts",
                    target="post",
                    parser=_parse_created_month_search_filter,
                    applier=_apply_post_created_month_search_filter,
                    syntax="created:YYYY-MM",
                    description="按回复创建月份过滤搜索结果。",
                ),
            ),
        )
    )

    registry.register_module(
        ForumModuleDefinition(
            module_id="posts",
            name="Posts",
            description="帖子流、回复实体、帖子类型与楼层内容输出。",
            category="feature",
            dependencies=("users",),
            capabilities=("post-stream", "post-detail", "post-types"),
            post_types=(
                PostTypeDefinition(
                    code="comment",
                    label="普通回复",
                    module_id="posts",
                    description="默认的讨论回复帖子类型，会参与回复统计、帖子流与全文搜索。",
                    icon="far fa-comment",
                    is_default=True,
                    is_stream_visible=True,
                    counts_toward_discussion=True,
                    counts_toward_user=True,
                    searchable=True,
                ),
                PostTypeDefinition(
                    code="discussionRenamed",
                    label="讨论改标题",
                    module_id="discussions",
                    description="记录讨论标题被修改的系统事件帖，不计入回复统计和全文搜索。",
                    icon="fas fa-heading",
                    is_default=False,
                    is_stream_visible=True,
                    counts_toward_discussion=False,
                    counts_toward_user=False,
                    searchable=False,
                ),
                PostTypeDefinition(
                    code="discussionLocked",
                    label="讨论锁定状态变更",
                    module_id="discussions",
                    description="记录讨论被锁定或解除锁定的系统事件帖，不计入回复统计和全文搜索。",
                    icon="fas fa-lock",
                    is_default=False,
                    is_stream_visible=True,
                    counts_toward_discussion=False,
                    counts_toward_user=False,
                    searchable=False,
                ),
                PostTypeDefinition(
                    code="discussionSticky",
                    label="讨论置顶状态变更",
                    module_id="discussions",
                    description="记录讨论被置顶或取消置顶的系统事件帖，不计入回复统计和全文搜索。",
                    icon="fas fa-thumbtack",
                    is_default=False,
                    is_stream_visible=True,
                    counts_toward_discussion=False,
                    counts_toward_user=False,
                    searchable=False,
                ),
                PostTypeDefinition(
                    code="discussionHidden",
                    label="讨论隐藏状态变更",
                    module_id="discussions",
                    description="记录讨论被隐藏或恢复显示的系统事件帖，不计入回复统计和全文搜索。",
                    icon="fas fa-eye-slash",
                    is_default=False,
                    is_stream_visible=True,
                    counts_toward_discussion=False,
                    counts_toward_user=False,
                    searchable=False,
                ),
                PostTypeDefinition(
                    code="postHidden",
                    label="回复隐藏状态变更",
                    module_id="posts",
                    description="记录回复被隐藏或恢复显示的系统事件帖，不计入回复统计和全文搜索。",
                    icon="fas fa-eye-slash",
                    is_default=False,
                    is_stream_visible=True,
                    counts_toward_discussion=False,
                    counts_toward_user=False,
                    searchable=False,
                ),
            ),
        )
    )

    registry.register_module(
        ForumModuleDefinition(
            module_id="users",
            name="Users",
            description="用户资料、用户组、权限分配与封禁管理。",
            category="feature",
            permissions=(
                PermissionDefinition(
                    code="viewUserList",
                    label="查看用户列表",
                    section="view",
                    section_label="查看权限",
                    module_id="users",
                    icon="fas fa-users",
                    description="允许浏览用户列表与公开资料。",
                ),
                PermissionDefinition(
                    code="searchUsers",
                    label="搜索用户",
                    section="view",
                    section_label="查看权限",
                    module_id="users",
                    icon="fas fa-search",
                    description="允许在论坛搜索中查询用户。",
                ),
                PermissionDefinition(
                    code="user.edit",
                    label="编辑用户资料",
                    section="user",
                    section_label="用户管理",
                    module_id="users",
                    icon="fas fa-user-edit",
                    description="允许管理员编辑任意用户资料与用户组。",
                ),
                PermissionDefinition(
                    code="user.suspend",
                    label="封禁用户",
                    section="user",
                    section_label="用户管理",
                    module_id="users",
                    icon="fas fa-user-slash",
                    description="允许暂停用户发言能力。",
                ),
            ),
            admin_pages=(
                AdminPageDefinition(
                    path="/admin/users",
                    label="用户管理",
                    icon="fas fa-users",
                    module_id="users",
                    nav_section="core",
                    description="查看、编辑、分组与封禁论坛用户。",
                ),
            ),
            capabilities=("profiles", "groups", "suspension"),
        )
    )

    registry.register_module(
        ForumModuleDefinition(
            module_id="realtime",
            name="Realtime",
            description="WebSocket 连接、通知实时推送和论坛实时信号。",
            category="infrastructure",
            capabilities=("websocket", "presence", "typing"),
            event_listeners=(
                EventListenerDefinition(
                    event="NotificationCreated",
                    listener="dispatch_notification_batch",
                    module_id="realtime",
                    description="通知创建后通过 WebSocket 批量推送到前端。",
                ),
            ),
        )
    )
